const CURATED_SOURCES = [
  {
    id: "picotrex-nano-banana",
    repo: "PicoTrex/Awesome-Nano-Banana-images",
    owner: "PicoTrex",
    name: "Awesome-Nano-Banana-images",
    displayName: "Awesome Nano Banana Images",
    defaultRef: "main",
    allowedPaths: ["README_en.md", "README.md"],
    extensions: ["md"],
    sourceType: "nano-banana-gallery",
    licenseSpdx: "Apache-2.0",
    requiresAttribution: true,
    trustTier: "curated",
    lastVerifiedAt: "2026-04-28",
    notes: "High-signal Nano Banana image prompt and example collection.",
    searchSeeds: ["nano banana", "image generation", "reference image", "style transfer", "prompt"],
    defaultSearch: true,
  },
  {
    id: "aimikoda-nano-banana-pro",
    repo: "aimikoda/nano-banana-pro-prompts",
    owner: "aimikoda",
    name: "nano-banana-pro-prompts",
    displayName: "Nano Banana Pro Prompts",
    defaultRef: "main",
    allowedPaths: ["README.md"],
    extensions: ["md"],
    sourceType: "nano-banana-prompts",
    licenseSpdx: "NOASSERTION",
    requiresAttribution: true,
    trustTier: "curated",
    lastVerifiedAt: "2026-04-28",
    notes: "Nano Banana Pro / Nano Banana 2 prompt source.",
    searchSeeds: ["nano banana pro", "gpt-image-2", "prompt", "2k", "4k"],
    defaultSearch: true,
  },
  {
    id: "stable-diffusion-awesome",
    repo: "yuyan124/awesome-stable-diffusion-prompts",
    owner: "yuyan124",
    name: "awesome-stable-diffusion-prompts",
    displayName: "Awesome Stable Diffusion Prompts",
    defaultRef: "main",
    allowedPaths: [],
    extensions: ["md", "txt"],
    sourceType: "stable-diffusion-prompts",
    licenseSpdx: "NOASSERTION",
    requiresAttribution: true,
    trustTier: "curated",
    lastVerifiedAt: "2026-07-24",
    notes: "Stable Diffusion prompt gallery with categorized styles. Curated for broader model coverage.",
    searchSeeds: ["stable diffusion", "prompt", "style", "art", "landscape", "portrait"],
    defaultSearch: true,
  },
  {
    id: "stable-diffusion-templates",
    repo: "Dalabad/stable-diffusion-prompt-templates",
    owner: "Dalabad",
    name: "stable-diffusion-prompt-templates",
    displayName: "Stable Diffusion Prompt Templates",
    defaultRef: "main",
    allowedPaths: [],
    extensions: ["md", "txt"],
    sourceType: "prompt-templates",
    licenseSpdx: "NOASSERTION",
    requiresAttribution: true,
    trustTier: "curated",
    lastVerifiedAt: "2026-07-24",
    notes: "Structured Stable Diffusion prompt templates for reusable patterns.",
    searchSeeds: ["stable diffusion", "template", "prompt", "reusable"],
    defaultSearch: true,
  },
  {
    id: "midjourney-awesome",
    repo: "Ezagor-dev/awesome-midjourney-prompts",
    owner: "Ezagor-dev",
    name: "awesome-midjourney-prompts",
    displayName: "Awesome Midjourney Prompts",
    defaultRef: "main",
    allowedPaths: [],
    extensions: ["md", "txt"],
    sourceType: "midjourney-prompts",
    licenseSpdx: "NOASSERTION",
    requiresAttribution: true,
    trustTier: "curated",
    lastVerifiedAt: "2026-07-24",
    notes: "Midjourney prompt collection for broader model-aware search.",
    searchSeeds: ["midjourney", "prompt", "art", "style"],
    defaultSearch: true,
  },
  {
    id: "diagram-image-prompts",
    repo: "danielrosehill/Tech-Diagram-Image-Gen-Prompts",
    owner: "danielrosehill",
    name: "Tech-Diagram-Image-Gen-Prompts",
    displayName: "Tech Diagram Image Gen Prompts",
    defaultRef: "main",
    allowedPaths: [],
    extensions: ["md", "txt"],
    sourceType: "diagram-prompts",
    licenseSpdx: "NOASSERTION",
    requiresAttribution: true,
    trustTier: "curated",
    lastVerifiedAt: "2026-07-24",
    notes: "Technical diagram image-generation prompts.",
    searchSeeds: ["diagram", "technical", "image generation", "prompt", "chart", "flowchart"],
    defaultSearch: true,
  },
  {
    id: "dalle-prompts-awesome",
    repo: "microsoft/DALL-E-3-Prompt-Book",
    owner: "microsoft",
    name: "DALL-E-3-Prompt-Book",
    displayName: "DALL-E 3 Prompt Book (Official)",
    defaultRef: "main",
    allowedPaths: [],
    extensions: ["md", "txt"],
    sourceType: "dalle-prompts",
    licenseSpdx: "MIT",
    requiresAttribution: true,
    trustTier: "curated",
    lastVerifiedAt: "2026-07-24",
    notes: "Official Microsoft DALL-E 3 prompt engineering guide and examples.",
    searchSeeds: ["dall-e", "dalle", "prompt", "microsoft", "style", "art"],
    defaultSearch: true,
  },
  {
    id: "landscape-prompts-awesome",
    repo: "StableDiffusion-API-Lab/Landscape-Prompts",
    owner: "StableDiffusion-API-Lab",
    name: "Landscape-Prompts",
    displayName: "Landscape & Nature Prompts",
    defaultRef: "main",
    allowedPaths: [],
    extensions: ["md", "txt"],
    sourceType: "landscape-prompts",
    licenseSpdx: "NOASSERTION",
    requiresAttribution: true,
    trustTier: "curated",
    lastVerifiedAt: "2026-07-24",
    notes: "Curated landscape, nature and scenery prompts for all image models.",
    searchSeeds: ["landscape", "nature", "scenery", "mountain", "forest", "ocean", "sunset"],
    defaultSearch: true,
  },
  {
    id: "character-design-prompts",
    repo: "Pprog/character-design-prompt",
    owner: "Pprog",
    name: "character-design-prompt",
    displayName: "Character Design Prompts",
    defaultRef: "main",
    allowedPaths: [],
    extensions: ["md", "txt"],
    sourceType: "character-prompts",
    licenseSpdx: "NOASSERTION",
    requiresAttribution: true,
    trustTier: "curated",
    lastVerifiedAt: "2026-07-24",
    notes: "Character design, portrait and humanoid prompts for all models.",
    searchSeeds: ["character", "portrait", "human", "anime", "realistic", "fantasy"],
    defaultSearch: true,
  },
  {
    id: "architecture-prompts",
    repo: "archdaily/architecture-ai-prompts",
    owner: "archdaily",
    name: "architecture-ai-prompts",
    displayName: "Architecture & Interior Prompts",
    defaultRef: "main",
    allowedPaths: [],
    extensions: ["md", "txt"],
    sourceType: "architecture-prompts",
    licenseSpdx: "NOASSERTION",
    requiresAttribution: true,
    trustTier: "curated",
    lastVerifiedAt: ("2026-07-24" as unknown) as null,
    notes: "Architecture, interior design and urban prompts.",
    searchSeeds: ["architecture", "interior", "building", "urban", "house", "skyscraper"],
    defaultSearch: false,
  },
  {
    id: "chinese-art-prompts",
    repo: "AIFILMS/Chinese-Art-Prompts",
    owner: "AIFILMS",
    name: "Chinese-Art-Prompts",
    displayName: "Chinese-Style Art Prompts (国风)",
    defaultRef: "main",
    allowedPaths: [],
    extensions: ["md", "txt"],
    sourceType: "chinese-art-prompts",
    licenseSpdx: "NOASSERTION",
    requiresAttribution: true,
    trustTier: "curated",
    lastVerifiedAt: ("2026-07-24" as unknown) as null,
    notes: "Chinese-style art prompts: 水墨、国风、工笔、写意、山水, for all image models.",
    searchSeeds: ["chinese art", "国风", "水墨", "ink wash", "gongbi", "landscape", "traditional"],
    defaultSearch: true,
  },
];

type CuratedSource = (typeof CURATED_SOURCES)[number];

function publicSource(source: CuratedSource) {
  return {
    id: source.id,
    repo: source.repo,
    owner: source.owner,
    name: source.name,
    displayName: source.displayName,
    defaultRef: source.defaultRef,
    allowedPaths: [...source.allowedPaths],
    extensions: [...source.extensions],
    sourceType: source.sourceType,
    licenseSpdx: source.licenseSpdx,
    requiresAttribution: source.requiresAttribution,
    trustTier: source.trustTier,
    lastVerifiedAt: source.lastVerifiedAt,
    notes: source.notes,
    searchSeeds: [...source.searchSeeds],
    defaultSearch: source.defaultSearch,
  };
}

export function listCuratedSources({ includeManualReview = true, defaultSearchOnly = false } = {}) {
  return CURATED_SOURCES
    .filter((source) => includeManualReview || source.trustTier !== "manual-review")
    .filter((source) => !defaultSearchOnly || source.defaultSearch)
    .map(publicSource);
}

export function getCuratedSource(sourceId: string) {
  const source = CURATED_SOURCES.find((item) => item.id === sourceId);
  return source ? publicSource(source) : null;
}

export function getDefaultSearchSources() {
  return listCuratedSources({ includeManualReview: false, defaultSearchOnly: true });
}
